{{ $basePath := "web" }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress-{{ .Values.cluster }}
  namespace: pathfinder
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: {{ .Values.ingress.sslTermination | quote }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header x-forwarded-path {{ $basePath | quote }};
      proxy_set_header x-forwarded-host {{ .Values.ingress.host | quote }};
      proxy_set_header x-forwarded-proto "https";
    nginx.ingress.kubernetes.io/server-snippet: |
      location = / {
        return 301 /{{$basePath}};
      }
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Chart.Name }}-{{ .Values.cluster }}
          servicePort: 80
        path: /
      - backend:
          serviceName: {{ .Chart.Name }}-{{ .Values.cluster }}
          servicePort: 80
        path: /{{ $basePath }}(/|$)(.*)
                
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Chart.Name }}-tls-{{ .Values.cluster }}
